# https://github.com/marketplace/actions/ubutu-lint
---
on: pull_request
name: ubuntu Linter
jobs:
  ubuntu-Linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: ubuntu-lint
        uses: ibiqlik/action-ubuntulint@v1
        with:
          strict: true
          config_file: ".github/workflows/.ubuntulint"
